version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=certificate_manager
      - POSTGRES_USER=certificate_manager
      - POSTGRES_PASSWORD=password
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=certificate_manager
      - POSTGRES_USER=certificate_manager
      - POSTGRES_PASSWORD=password
    depends_on:
      - db